services:
  bot:
    image: ghcr.io/vldc-hq/vldc-bot/bot:latest
    env_file:
      - ./.env

    volumes:
      - ./:/opt/gcloud
    logging:
      options:
        max-size: "1M"
        max-file: "10"
